### ISSUE TITLE
synthesizer-io-wasm does not build with rust 1.32

### ISSUE THREAD

**Issue by zacharydenton** [raphlinus/synthesizer-io#3]
```
rustc 1.32.0-nightly (b68fc18c4 2018-11-27)
```

```
error[E0635]: unknown feature `wasm_custom_section`
  --> src/lib.rs:17:44
   |
17 | #![feature(proc_macro, wasm_import_module, wasm_custom_section)]
   |                                            ^^^^^^^^^^^^^^^^^^^

error[E0635]: unknown feature `wasm_import_module`
  --> src/lib.rs:17:24
   |
17 | #![feature(proc_macro, wasm_import_module, wasm_custom_section)]
   |                        ^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0635`.
error: Could not compile `synthesizer-io-wasm`.
```

To fix this issue, I removed this line: https://github.com/raphlinus/synthesizer-io/blob/09810aac0a4c5edfe1d89a74bb81675c2c3f3059/synthesizer-io-wasm/src/lib.rs#L17
